---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: atat
spec:
  minReplicas: 3
  maxReplicas: 6
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: atat-worker
spec:
  minReplicas: 1
  maxReplicas: 3
