---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: atst
spec:
  minReplicas: 3
  maxReplicas: 6
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: atst-worker
spec:
  minReplicas: 1
  maxReplicas: 3
