---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  AZURE_STORAGE_ACCOUNT_NAME: dryruntasks
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: "https://tenants-dryrun-keyvault.vault.azure.net/"
  CAC_URL: https://auth-bugbounty.atat.dev/login-redirect
  CELERY_DEFAULT_QUEUE: celery-bugbounty
  CSP: hybrid
  FLASK_ENV: bugbounty
  PGDATABASE: cloudzero_dryrun_bugbounty
  PGHOST: cloudzero-dryrun-sql.postgres.database.azure.com
  PGUSER: atat@cloudzero-dryrun-sql
  REDIS_HOST: cloudzero-dryrun-redis.redis.cache.windows.net:6380
  SERVER_NAME: bugbounty.atat.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  ASSETS_URL: ""
  AZURE_STORAGE_ACCOUNT_NAME: dryruntasks
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: "https://tenants-dryrun-keyvault.vault.azure.net/"
  BLOB_STORAGE_URL: https://dryruntasks.blob.core.windows.net/
  CAC_URL: https://auth-bugbounty.atat.dev/login-redirect
  CDN_ORIGIN: https://bugbounty.atat.dev
  CELERY_DEFAULT_QUEUE: celery-bugbounty
  CSP: hybrid
  FLASK_ENV: bugbounty
  PGDATABASE: cloudzero_dryrun_bugbounty
  PGHOST: cloudzero-dryrun-sql.postgres.database.azure.com
  PGUSER: atat@cloudzero-dryrun-sql
  REDIS_HOST: cloudzero-dryrun-redis.redis.cache.windows.net:6380
  SESSION_COOKIE_DOMAIN: atat.dev
  STATIC_URL: "https://bugbounty.atat.dev/static/"
  SAML_ENTITY_ID: https://bugbounty.atat.dev
  SAML_ACS: https://bugbounty.atat.dev/login?acs
  SAML_SLS: https://bugbounty.atat.dev/login?sls
  SAML_IDP_URI: https://fs.disa.mil/federationmetadata/2007-06/federationmetadata.xml
  SAML_DEV_ENTITY_ID: https://bugbounty.atat.dev/login-dev
  SAML_DEV_ACS: https://bugbounty.atat.dev/login-dev?acs
  SAML_DEV_SLS: https://bugbounty.atat.dev/login-dev?sls
  SAML_DEV_IDP_URI: https://login.microsoftonline.com/ab154c46-3d57-4386-9b87-8002123f3858/federationmetadata/2007-06/federationmetadata.xml?appid=cdfe7a83-6be4-41ca-b96c-4a3718d3612c
