- name: get the circle ci api token
  import_tasks: source_api_token.yml

- name: get tf outputs
  include_role:
    name: terraform
  vars:
    deploy_app_env: false

- name: run circle ci ops build
  import_tasks: run_ops_build.yml
  when: build_and_push_ops_image == true

- name: run circle ci app build
  import_tasks: run_app_build.yml
  when: build_and_push_app_images == true
