---
# - name: Kick off a build for image
#   uri:
#     url: "https://circleci.com/api/v2/project/{{circle_ci_project}}/pipeline"
#     method: POST
#     headers:
#       Circle-Token: "{{ circle_ci_api_key }}"
#     body:
#       branch: "{{ branch_to_build }}"
#       parameters:
#         container_registry: "{{ container_registry }}"
#         sp: "{{ lookup('env', 'ARM_CLIENT_ID_BUILD' ) }}"
#         sp_object_id: "{{ lookup('env','TF_VAR_OPS_OID') }}"
#         sp_password: "{{ lookup('env', 'ARM_CLIENT_SECRET_BUILD' ) }}"
#         operator_sp_url: "{{ lookup('env','AZ_CLI_SP') }}"
#         ops_registry: "{{ ops_registy }}"
#         ops_subscription_id: "{{ lookup('env','SUBSCRIPTION_ID') }}"
#         build_and_push_ops_image: "{{ build_and_push_ops_image }}"
#         build_and_push_app_images: "{{ build_and_push_app_images }}"
#         tenant_id: "{{ lookup('env','SUBSCRIPTION_TENANT') }}"
#     body_format: json
#     status_code:
#       - 201
#   register: _result

- name: Copy ops image to new registry
  shell: az acr import --name {{ container_registry }} --source {{ ops_registy }}/opsdeploy:poc-crt --image ops
  register: verification
  changed_when: verification.rc == 1
  ignore_errors: yes

# - name: Fetch latest `ops` image from {{ tf_bootstrap_backend_outputs.ops_container_registry_name.value }}
#   shell: az acr repository show-tags --top 1 --orderby time_desc --repository ops --name {{ tf_bootstrap_backend_outputs.ops_container_registry_name.value }}
#   register: ops_bastion_image
#   retries: 500
#   delay: 60
#   until: ops_bastion_image is not failed
