---
- name: Kick off a build for image
  uri:
    url: "https://circleci.com/api/v2/project/{{circle_ci_project}}/pipeline"
    method: POST
    headers:
      Circle-Token: "{{ circle_ci_api_key }}"
    body:
      branch: "{{ branch_to_build }}"
      parameters:
        container_registry: "{{ tf_app_env_outputs.container_registry_name.value }}"
        subscription_id: "{{ tf_app_env_outputs.subscription_id.value }}"
        atat_image_tag: "{{ tf_app_env_outputs.container_registry_name.value}}.azurecr.io/atat:latest"
        nginx_image_tag: "{{ tf_app_env_outputs.container_registry_name.value}}.azurecr.io/nginx:latest"
        sp: "{{ lookup('env', 'ARM_CLIENT_ID_BUILD' ) }}"
        sp_object_id: "{{ lookup('env','TF_VAR_OPS_OID') }}"
        sp_password: "{{ lookup('env', 'ARM_CLIENT_SECRET_BUILD' ) }}"
        operator_sp_url: "{{ lookup('env','AZ_CLI_SP') }}"
        ops_registry:  "{{ ops_registy }}"
        ops_subscription_id: "{{ lookup('env','SUBSCRIPTION_ID') }}"
        build_and_push_app_images: "{{ build_and_push_app_images }}"
        tenant_id:  "{{ lookup('env','SUBSCRIPTION_TENANT') }}"
    body_format: json
    status_code:
      - 201
  register: _result
