- name: show tf outputs
  debug:
    msg: "{{ tf_bootstrap_backend_outputs }}"

- name: build backend
  set_fact:
    b_end: "{{ b_end|default({}) | combine( { item : tf_bootstrap_backend_outputs[item].value } ) }}"
  with_items: "{{ tf_bootstrap_backend_outputs }}"

- name: debug be
  debug:
    msg: "{{ b_end }}"
