---
- name: get backend config
  import_tasks: get_backend.yml

- name: get backend config
  import_tasks: source_vars_from_storage_account.yml

- name: get variables
  import_tasks: get_variables.yml

- name: deploy application env
  import_tasks: setup.yml
  when: deploy_app_env == true

- name: show outputs
  import_tasks: show_outputs.yml
  when: show_app_env_outputs == true
