---
- name: get backend config
  import_tasks: get_backend.yml

- name: get variables
  import_tasks: get_variables.yml

- name: deploy application env
  import_tasks: setup.yml
  when: deploy_app_env is defined


- name: teardown application env
  import_tasks: teardown.yml
  when: teardown_app_env is defined

- name: show outputs
  import_tasks: show_outputs.yml
  when: show_app_env_outputs is defined
