name: Locust Load Test

on: [push]

jobs:
  build:
    name: 'Locust Load Test'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Load Test
        uses: dod-ccpo/atat@develop
        with:
          LOCUSTFILE: "load-test/locustfile.py"
          URL:  "https://demo.atat.dev"
          USERS: "10"
          RATE: "2"
          RUNTIME: "60s"