- name: unpack
  set_fact:
    unpacked: "{{ secrets_env[deploy_tag] }}"

- set_fact:
    kv_tf: "{{ kv_tf|default({}) | combine({ item.name : (item_no_quotes | regex_replace(\"'\",'\"'))  }) }}"
  vars:
    item_no_quotes: "{{ (item.value | regex_replace(\"'\",'')) if item.type=='' else (item.value|regex_replace(\"'\",'\"')) }}"
  with_items: "{{unpacked}}"

- name: show_kv_tf
  debug:
    msg: "{{ kv_tf }}"
