
- name: get secrets
  vars:
    url:  "{{ vault_url }}"
    ops_keyvault_client_id: "{{ vault_client_id }}"
    ops_keyvault_secret:    "{{ vault_secret }}"
    ops_keyvault_tenant:  "{{ vault_tenant }}"
    secretname: "tf-{{ deploy_tag | regex_replace('\\.','-') }}"
  set_fact:
<<<<<<< HEAD
    secrets_env: "{{ lookup('azure_keyvault_secret',secretname, vault_url=url, client_id=vault_client_id, secret=vault_secret, tenant_id=vault_tenant) | from_yaml }}"
=======
    secrets_env: "{{ secrets_env|default({})   | combine( { deploy_tag:  (lookup('azure_keyvault_secret',secretname, vault_url=url, client_id=vault_client_id, secret=vault_secret, tenant_id=vault_tenant))  }) }}"
<<<<<<< HEAD
>>>>>>> DRYs up formatting to a single task, fixes quotes issue
=======
>>>>>>> 0234d0a2f8b0a819e35db36751ad50d71879634c

- name: Include get_secrets
  include_tasks: "{{role_path}}/tasks/format_secrets.yml"
