---
- name: source the secrets
  import_tasks: source_secrets.yml

- name: bootstrap keyvault with terraform vars
  import_tasks: bootstrap_terraform_secrets.yml

- name: store secrets as plain key=value
  import_tasks: secret.yml

- name: secrets to json file
  import_tasks: secrets_to_json_file.yml
  when: secrets_to_file is defined

- name: wipe secrets
  import_tasks: wipe_secrets.yml
  when: wipe_secrets is defined

- name: get secrets
  import_tasks: get_secrets.yml
  when: get_secrets is defined
