---
- name: bootstrap keyvault with terraform vars
  import_tasks: bootstrap_terraform_secrets.yml 
  when: bootstrap_terraform is defined


- name: secrets to json file
  import_tasks: secrets_to_json_file.yml
  when: secrets_to_file is defined


- name: wipe secrets
  import_tasks: wipe_secrets.yml
  when: wipe_secrets is defined


- name: get secrets
  import_tasks: get_secrets.yml
<<<<<<< HEAD
<<<<<<< HEAD
  when: get_secrets is defined
=======
  when: get_secrets is defined 
>>>>>>> DRYs up formatting to a single task, fixes quotes issue
=======
  when: get_secrets is defined 
>>>>>>> 0234d0a2f8b0a819e35db36751ad50d71879634c
