


- name: set vault deploy tag
  set_fact:
    dep_tag: "tf-{{ deploy_tag | regex_replace('\\.','-') }}"
- name: get secrets
  vars:
    url:  "{{ vault_url }}"
    ops_keyvault_client_id: "{{ vault_client_id }}"
    ops_keyvault_secret:    "{{ vault_secret }}"
    ops_keyvault_tenant:  "{{ vault_tenant }}"
    secretname: "tf-{{ deploy_tag | regex_replace('\\.','-') }}"
  set_fact:
    secrets_env: "{{ secrets_env|default({})   | combine( { deploy_tag:  (lookup('azure_keyvault_secret',secretname, vault_url=url, client_id=vault_client_id, secret=vault_secret, tenant_id=vault_tenant))  }) }}"


- name: prestuff
  debug:
    msg:  "{{ secrets_env | to_json }}"



- name: to json file
  set_fact:
    json_fmt: "{{ secrets_env[deploy_tag] }}"

- set_fact:
    kv_tf: "{{ kv_tf|default({}) | combine({ item.name : (item_no_quotes)  })   }}"
  vars:
    item_no_quotes: "{{ (item.value | regex_replace(\"'\",'')) if item.type=='' else (item.value|regex_replace(\"'\",'\"')) }}"
  with_items: "{{json_fmt}}"


- debug:
    msg: "{{ kv_tf }}"



- name: write file
  copy:
    dest: ./json_vars
    content: "{{ kv_tf | to_nice_json}}"
