- name: set vault deploy tag
  set_fact:
    dep_tag: "tf-{{ deploy_tag | regex_replace('\\.','-') }}"

- name: Include get_secrets
  include_tasks: "{{ role_path }}/tasks/get_secrets.yml"

- name: prestuff
  debug:
    msg: "{{ secrets_env | to_json }}"

- name: to json file
  set_fact:
    json_fmt: "{{ secrets_env }}"

- name: Set fact "kv_tf"
  set_fact:
    kv_tf: "{{ kv_tf|default({}) | combine({ item : secrets_env[item] }) }}"
  with_items: "{{ json_fmt }}"

- name: Show variable "kv_tf"
  debug:
    msg: "{{ kv_tf }}"

- name: write file
  copy:
    dest: "{{ tf_dir }}/retrieved_tfvars.{{ deploy_tag }}.tfvars.json"
    content: "{{ kv_tf | to_nice_json }}"
