


export AKS_SP_INFO=$(az ad sp create-for-rbac)
export AKS_SP_CLIENT_ID=$(echo $AKS_SP_INFO | jq -r .appId)
export AKS_SP_CLIENT_SECRET=$(echo $AKS_SP_INFO | jq -r .password)
export AKS_SP_OBJECT_ID=$(az ad sp show --id $AKS_SP_CLIENT_ID | jq -r .objectId)
export POSTGRES_ROOT_PASSWORD=$(poetry run python -c "import secrets; print(secrets.token_urlsafe(32))")
export POSTGRES_ROOT_USER="clouzero_pg_admin"
az keyvault secret set --vault-name [operator key vault] --name k8s-client-id --value $AKS_SP_CLIENT_ID
az keyvault secret set --vault-name [operator key vault] --name k8s-object-id --value $AKS_SP_OBJECT_ID
az keyvault secret set --vault-name [operator key vault] --name k8s-client-secret --value $AKS_SP_CLIENT_SECRET
az keyvault secret set --vault-name [operator key vault] --name postgres-root-password --value $POSTGRES_ROOT_PASSWORD
az keyvault secret set --vault-name [operator key vault] --name postgres-root-user --value $POSTGRES_ROOT_USER



- name: Create a secret
  azure_rm_keyvaultsecret:
    secret_name: MySecret
    secret_value: My_Pass_Sec
    keyvault_uri: https://contoso.vault.azure.net/
    tags:
        testing: testing
        delete: never

        
