---

init_tf: yes
deploy_app_env: true
show_app_env_outputs: true
tf_base_dir: /src/terraform/providers
tf_subdir: application_env
tfvars_file_name: app.tfvars.json
application_subscription_id: "{{ lookup('env','SUBSCRIPTION_ID') }}"
terraform_dir: "{{ tf_dir }}"
terraform_deploy_version: "{{ deploy_tag }}"
keyvault_list_service_principle_client_id: "{{ vault_client_id }}"
keyvault_list_service_principle_secret:    "{{ vault_secret }}"
keyvault_list_service_principle_tenant:  "{{ vault_tenant }}"
