apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atat
spec:
  template:
    spec:
      volumes:
        - name: nginx-secret
          flexVolume:
            options:
              keyvaultname: "atat-vault-test"
              keyvaultobjectnames: "dhparam4096;staging-cert;staging-cert"
        - name: flask-secret
          flexVolume:
            options:
              keyvaultname: "atat-vault-test"
              keyvaultobjectnames: "staging-AZURE-STORAGE-KEY;staging-MAIL-PASSWORD;staging-PGPASSWORD;staging-REDIS-PASSWORD;staging-SECRET-KEY"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atat-worker
spec:
  template:
    spec:
      volumes:
        - name: flask-secret
          flexVolume:
            options:
              keyvaultname: "atat-vault-test"
              keyvaultobjectnames: "staging-AZURE-STORAGE-KEY;staging-MAIL-PASSWORD;staging-PGPASSWORD;staging-REDIS-PASSWORD;staging-SECRET-KEY"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atat-beat
spec:
  template:
    spec:
      volumes:
        - name: flask-secret
          flexVolume:
            options:
              keyvaultname: "atat-vault-test"
              keyvaultobjectnames: "staging-AZURE-STORAGE-KEY;staging-MAIL-PASSWORD;staging-PGPASSWORD;staging-REDIS-PASSWORD;staging-SECRET-KEY"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crls
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: flask-secret
              flexVolume:
                options:
                  keyvaultname: "atat-vault-test"
                  keyvaultobjectnames: "staging-AZURE-STORAGE-KEY;staging-MAIL-PASSWORD;staging-PGPASSWORD;staging-REDIS-PASSWORD;staging-SECRET-KEY"
