---
apiVersion: v1
kind: Service
metadata:
  name: atat-main
spec:
  loadBalancerIP: 40.76.217.62
  ports:
  - port: 80
    targetPort: 9342
    name: http
  - port: 443
    targetPort: 9442
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: atat-auth
spec:
  loadBalancerIP: 40.87.14.233
  ports:
  - port: 80
    targetPort: 9343
    name: http
  - port: 443
    targetPort: 9443
    name: https
