version: 2.1

parameters:
  subscription_id:
    type: string
    default: ${AZURE_SUBSCRIPTION}
  container_registry:
    type: string
    default: ${AZURE_REGISTRY}
  tenant_id:
    type: string
    default: ${AZURE_SP_TENANT}
  sp:
    type: string
    default: ${AZURE_SP}
  sp_password:
    type: string
    default: ${AZURE_SP_PASSWORD}
  sp_object_id:
    type: string
    default: "__NONE__"
  operator_sp_url:
    type: string
    default: "__NONE__"
  container_env:
    type: string
    default: -e PGHOST=postgres -e REDIS_HOST=redis:6379
  azure_server_name:
    type: string
    default: ${AZURE_SERVER_NAME}
  namespace:
    type: string
    default: atat
  atat_image_tag:
    type: string
    default: ${AZURE_REGISTRY}.azurecr.io/atat:latest
  nginx_image_tag:
    type: string
    default: ${AZURE_REGISTRY}.azurecr.io/nginx:latest
  cluster_name:
    type: string
    default: ${CLUSTER_NAME}
  resource_group:
    type: string
    default: ${RESOURCE_GROUP}
  build_and_push_app_images:
    description: Causes a build with a single stage that creates and pushes atat and docker images docker images to a container registry only.
    type: boolean
    default: false
  build_and_push_ops_image:
    description: Causes a build with a single stage that creates and pushes the ops deployment image to a container registry only.
    type: boolean
    default: false
  ops_registry:
    description: The name of the registry (not including the azureacr suffix).
    type: string
    default: "cloudzeroopsregistry"

commands:
  azlogin:
    parameters:
      registry:
        description: The name of the registry (not including the azureacr suffix).
        type: string
      subscription_id:
        description: Target subscription the registry exists under.
        type: string
    steps:
      - run:
          name: Install Azure CLI
          command: |
            apk update
            apk add bash py3-pip
            apk add --virtual=build \
              linux-headers gcc libffi-dev musl-dev openssl-dev python3-dev make curl
            pip3 --no-cache-dir install -U pip
            pip3 --no-cache-dir install azure-cli
            curl -L https://aka.ms/acr/installaad/bash | /bin/bash
            apk del --purge build
      - run:
          name: Login to Azure CLI
          shell: /bin/sh
          command: |
            az login \
              --service-principal \
              --tenant << pipeline.parameters.tenant_id >> \
              --password << pipeline.parameters.sp_password >> \
              --username << pipeline.parameters.sp >>
            az account set -s << parameters.subscription_id >>
            echo "Successfully logged in to Azure CLI."
            az acr login --name << parameters.registry >> | grep "Succeeded"
  cache_docker_images:
    steps:
      - run:
          name: Save the docker images to a cache
          command: |
            mkdir -p docker-cache
            docker save -o docker-cache/atat.tar atat:latest
            docker save -o docker-cache/builder.tar atat:builder
      - save_cache:
          key: docker-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - docker-cache
  restore_docker_image:
    steps:
      - restore_cache:
          keys:
            - docker-cache-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Restore Docker image from cache
          command: |
            docker load < docker-cache/atat.tar
            docker load < docker-cache/builder.tar
  setup_datastores:
    parameters:
      pgdatabase:
        type: string
        default: atat_test
    steps:
      - run:
          name: remove temp network if exists
          command: if docker network ls | grep atat  ; then docker network rm atat; fi
      - run:
          name: Set up temporary docker network
          command: docker network create atat
      - run:
          name: Start redis
          command: docker run -d --network atat --link redis:redis -p 6379:6379 --name redis circleci/redis:4-alpine3.8
      - run:
          name: Start postgres
          command: docker run -d --network atat --link postgres:postgres -p 5432:5432 --name postgres circleci/postgres:10-alpine-ram
      - run:
          name: Wait for containers
          command: sleep 3
      - run:
          name: Create database
          command: "docker exec postgres createdb -U postgres << parameters.pgdatabase >>"
      - run:
          name: Apply migrations
          command: docker run --network atat -e PGDATABASE=<< parameters.pgdatabase >> << pipeline.parameters.container_env >> atat:builder .venv/bin/python .venv/bin/alembic upgrade head
      - run:
          name: Apply the default permission sets
          command: docker run --network atat -e PGDATABASE=<< parameters.pgdatabase >> << pipeline.parameters.container_env >> atat:builder .venv/bin/python script/seed_roles.py

  deploy:
    parameters:
      namespace:
        type: string
        default: << pipeline.parameters.namespace >>
      atat_image_tag:
        type: string
        default: << pipeline.parameters.atat_image_tag >>
      nginx_image_tag:
        type: string
        default: << pipeline.parameters.nginx_image_tag >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - azlogin:
          subscription_id: << pipeline.parameters.subscription_id >>
          registry: << pipeline.parameters.container_registry >>
      - restore_docker_image
      - run:
          name: Build nginx image
          command: docker build -t nginx:latest --build-arg IMAGE=<< pipeline.parameters.container_registry >>.azurecr.io/rhelubi:8.2 - < nginx.Dockerfile
      - run:
          name: Tag images
          command: |
            docker tag atat:latest << pipeline.parameters.atat_image_tag >>
      - run:
          name: Push image
          command: |
            docker push << pipeline.parameters.atat_image_tag >>

jobs:
  docker-build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - azlogin:
          subscription_id: << pipeline.parameters.subscription_id >>
          registry: << pipeline.parameters.container_registry >>
      - run:
          name: Build images
          command: |
            docker build . --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg IMAGE=<< pipeline.parameters.container_registry >>.azurecr.io/rhel-py -f ./Dockerfile -t atat:builder --target builder
            docker build . --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg IMAGE=<< pipeline.parameters.container_registry >>.azurecr.io/rhel-py -f ./Dockerfile -t atat:latest
      - cache_docker_images

  test:
    docker:
      - image: docker:18.06.0-ce-git
      - image: circleci/postgres:10-alpine-ram
      - image: circleci/redis:4-alpine3.8
    environment:
      TF_VERSION: "0.12.24"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_docker_image
      - setup_datastores:
          pgdatabase: atat_test
      - run:
          name: Run CI tests
          command: |
            docker run \
              -e PGHOST=postgres \
              -e REDIS_HOST=redis:6379 \
              --network atat \
              atat:builder \
              /bin/sh -c "poetry install --no-root &&
                          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /install/tf.zip &&
                          unzip /install/tf.zip -d /bin/ &&
                          /bin/sh script/cibuild"

  integration-tests:
    docker:
      - image: docker:18.06.0-ce-git
      - image: circleci/postgres:10-alpine-ram
      - image: circleci/redis:4-alpine3.8
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_docker_image
      - setup_datastores:
          pgdatabase: atat
      - run:
          name: Start application container
          command: |
            docker run -d \
            -e PGHOST=postgres \
            -e REDIS_HOST=redis:6379 \
            -p 8000:8000 \
            --network atat \
            --name test-atat \
            atat:builder \
            /bin/sh -c "
              echo CLOUD_PROVIDER=mock > .env &&\
              yarn build &&\
              pip3 install uwsgi &&\
              uwsgi \
              --callable app \
              --module app \
              --plugin python3 \
              --virtualenv /install/.venv \
              --http-socket :8000
            "
      - run:
          name: Wait for ATAT container to be available
          command: |
            docker pull curlimages/curl:latest
            docker run --network atat \
              curlimages/curl:latest \
              curl --connect-timeout 3 \
              --max-time 5 \
              --retry 120 \
              --retry-connrefused \
              --retry-delay 1 \
              --retry-max-time 120 \
              test-atat:8000
      - run:
          name: Execute Ghost Inspector test suite
          command: |
            docker pull ghostinspector/test-runner-standalone:latest
            docker run \
              -e NGROK_TOKEN=$NGROK_TOKEN \
              -e GI_API_KEY=$GI_API_KEY \
              -e GI_SUITE=$GI_SUITE \
              -e GI_PARAMS_JSON='{}' \
              -e APP_PORT="test-atat:8000" \
              --network atat \
              ghostinspector/test-runner-standalone:latest

  deploy-staging:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - deploy:
          namespace: staging
          atat_image_tag: << pipeline.parameters.container_registry >>.azurecr.io/atat:staging-${CIRCLE_SHA1}
          nginx_image_tag: << pipeline.parameters.container_registry >>.azurecr.io/nginx:staging-${CIRCLE_SHA1}

  deploy-master:
    parameters:
      container_registry:
        type: string
        default: ${AZURE_REGISTRY}
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - deploy:
          namespace: master
          atat_image_tag: << pipeline.parameters.container_registry >>.azurecr.io/atat:master-${CIRCLE_SHA1}
          nginx_image_tag: << pipeline.parameters.container_registry >>.azurecr.io/nginx:master-${CIRCLE_SHA1}
  
  push-app-images:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - azlogin:
          subscription_id: << pipeline.parameters.subscription_id >>
          registry: << pipeline.parameters.ops_registry >>
      - run:
          name: Build images
          command: |
            docker build . --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg IMAGE=<< pipeline.parameters.ops_registry >>.azurecr.io/rhel-py -f ./Dockerfile -t atat:builder --target builder
            docker build . --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg IMAGE=<< pipeline.parameters.ops_registry >>.azurecr.io/rhel-py -f ./Dockerfile -t atat:latest
      - run:
          name: Build nginx image
          command: docker build -t nginx:latest --build-arg IMAGE=<< pipeline.parameters.ops_registry >>.azurecr.io/rhelubi:8.2 - < nginx.Dockerfile
      - run:
          name: Tag images
          command: |
            docker tag atat:latest << pipeline.parameters.atat_image_tag >>
            docker tag nginx:latest << pipeline.parameters.nginx_image_tag >>
      - run:
          name: Log into the target registry
          command: az acr login --name << pipeline.parameters.container_registry >> | grep "Succeeded"
      - run:
          name: Push image
          command: |
            docker push << pipeline.parameters.atat_image_tag >>
            docker push << pipeline.parameters.nginx_image_tag >>

  push-ops-image:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - azlogin:
          subscription_id: << pipeline.parameters.subscription_id >>
          registry: << pipeline.parameters.ops_registry >>
      - run:
          name: Build ops deployment image image
          command: |
            docker build -t ops:latest \
            --build-arg IMAGE=<< pipeline.parameters.ops_registry >>.azurecr.io/rhelubi:8.2 \
            --build-arg operator_sp_client_id=<< pipeline.parameters.sp >> \
            --build-arg operator_sp_object_id=<< pipeline.parameters.sp_object_id >> \
            --build-arg operator_sp_secret=<< pipeline.parameters.sp_password >> \
            --build-arg azure_tenant=<< pipeline.parameters.tenant_id >> \
            --build-arg azure_subscription_id=<< pipeline.parameters.subscription_id >> \
            --build-arg operator_sp_url=<< pipeline.parameters.operator_sp_url >> \
            . < Dockerfile.ops
      - run:
          name: Tag ops image
          command: docker tag ops:latest << pipeline.parameters.ops_registry >>.azurecr.io/ops:latest
      - run:
          name: Push ops image
          command: docker push << pipeline.parameters.ops_registry >>.azurecr.io/ops:latest

workflows:
  version: 2
  run-tests:
    when:
      not: 
        and: 
          - << pipeline.parameters.build_and_push_app_images >>
          - << pipeline.parameters.build_and_push_ops_image >>
    jobs:
      - docker-build
      - test:
          requires:
            - docker-build
      - integration-tests:
          requires:
            - docker-build
          filters:
            branches:
              only:
                - staging
                - master
      - deploy-staging:
          requires:
            - test
            - integration-tests
          filters:
            branches:
              only:
                - staging
      - deploy-master:
          requires:
            - test
            - integration-tests
          filters:
            branches:
              only:
                - master
  
  push-app-images:
    when: << pipeline.parameters.build_and_push_app_images >>
    jobs:
      - push-app-images

  push-ops-image:
    when: << pipeline.parameters.build_and_push_ops_image >>
    jobs:
      - push-ops-image
