version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: secrets-tool.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: INFO
    handlers: [console]
    propogate: yes

loggers:
    root:
        level: INFO
        handlers: [console]
        propogate: no
    click:
        level: INFO
        handlers: [console]
        propogate: yes
    azure.keyvault:
        level: INFO
        handlers: [console]
        propogate: yes
    azure.core:
        level: ERROR
        handlers: [console]
        propogate: no
    utils.keyvault.secrets:
        level: DEBUG
        handlers: [console]
        propogate: yes
    utils.terraform.wrapper:
        level: DEBUG
        handlers: [console]
        propogate: yes
    commands:
        level: INFO
        handlers: [console]
        propogate: yes
    main:
        level: INFO
        handlers: [console]
        propogate: no

