---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  AZURE_ACCOUNT_NAME: pwdevtasks
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: "https://tenants-pwdev-keyvault.vault.azure.net/"
  CELERY_DEFAULT_QUEUE: celery-staging
  CSP: hybrid
  FLASK_ENV: staging
  PGDATABASE: cloudzero_pwdev_atat
  PGHOST: 191.238.6.43
  PGUSER: atat@cloudzero-pwdev-sql
  PGSSLMODE: require
  REDIS_HOST: cloudzero-pwdev-redis.redis.cache.windows.net:6380
  SERVER_NAME: staging.atat.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  ASSETS_URL: ""
  AZURE_ACCOUNT_NAME: pwdevtasks
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: "https://tenants-pwdev-keyvault.vault.azure.net/"
  BLOB_STORAGE_URL: https://pwdevtasks.blob.core.windows.net/
  CAC_URL: https://auth-staging.atat.dev/login-redirect
  CDN_ORIGIN: https://staging.atat.dev
  CELERY_DEFAULT_QUEUE: celery-staging
  CSP: hybrid
  FLASK_ENV: staging
  PGDATABASE: cloudzero_pwdev_atat
  PGHOST: 191.238.6.43
  PGUSER: atat@cloudzero-pwdev-sql
  PGSSLMODE: require
  REDIS_HOST: cloudzero-pwdev-redis.redis.cache.windows.net:6380
  SESSION_COOKIE_DOMAIN: atat.dev
  STATIC_URL: "https://staging.atat.dev/static/"
