---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  AZURE_STORAGE_ACCOUNT_NAME: {{ tf_app_env_outputs.azure_storage_account_name.value }}
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: {{ tf_app_env_outputs.application_keyvault_url.value }}
  CELERY_DEFAULT_QUEUE: celery-{{ namespace }}
  CSP: hybrid
  FLASK_ENV: {{ namespace }}
  PGDATABASE: {{ tf_app_env_outputs.atat_database_name.value }}
  PGHOST: {{ tf_app_env_outputs.pg_host.value }}
  PGUSER: {{ tf_app_env_outputs.atat_user_name.value }}@{{ tf_app_env_outputs.atat_database_instance_name.value }}
  PGSSLMODE: verify-full
  REDIS_HOST: {{ tf_app_env_outputs.redis_hostname.value }}:{{ tf_app_env_outputs.redis_ssl_port.value }}
  REDIS_SSLMODE: required
  SERVER_NAME: {{ namespace }}.atat.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  ASSETS_URL:
  AZURE_STORAGE_ACCOUNT_NAME: {{ tf_app_env_outputs.azure_storage_account_name.value }}
  AZURE_POWERSHELL_CLIENT_ID: 1950a258-227b-4e31-a9cf-717495945fc2
  AZURE_TENANT_ADMIN_USERNAME: hybrid.admin@atathybrid.onmicrosoft.com
  AZURE_VAULT_URL: {{ tf_app_env_outputs.application_keyvault_url.value }}
  BLOB_STORAGE_URL: https://{{ namespace }}tasks.blob.core.windows.net/
  CDN_ORIGIN: https://{{ namespace }}.atat.dev
  CELERY_DEFAULT_QUEUE: celery-{{ namespace }}
  CSP: hybrid
  FLASK_ENV: {{ namespace }}
  PGDATABASE: {{ tf_app_env_outputs.atat_database_name.value }}
  PGHOST: {{ tf_app_env_outputs.pg_host.value }}
  PGUSER: {{ tf_app_env_outputs.atat_user_name.value }}@{{ tf_app_env_outputs.atat_database_instance_name.value }}
  PGSSLMODE: verify-full
  REDIS_HOST: {{ tf_app_env_outputs.redis_hostname.value }}:{{ tf_app_env_outputs.redis_ssl_port.value }}
  REDIS_SSLMODE: verify-full
  SESSION_COOKIE_DOMAIN: atat.dev
  STATIC_URL: https://{{ namespace }}.atat.dev/static/
  SAML_ENTITY_ID: https://{{ namespace }}.atat.dev
  SAML_ACS: https://{{ namespace }}.atat.dev/login?acs
  SAML_SLS: https://{{ namespace }}.atat.dev/login?sls
  SAML_IDP_URI: https://fs.disa.mil/federationmetadata/2007-06/federationmetadata.xml
  SAML_DEV_ENTITY_ID: https://{{ namespace }}.atat.dev/login-dev?saml
  SAML_DEV_ACS: https://{{ namespace }}.atat.dev/login-dev?acs
  SAML_DEV_SLS: https://{{ namespace }}.atat.dev/login-dev?sls
  SAML_DEV_IDP_URI: https://login.microsoftonline.com/b5ab0e1e-09f8-4258-afb7-fb17654bc5b3/federationmetadata/2007-06/federationmetadata.xml?appid=41b24b41-dad9-470a-94f2-10b11a71f8ea
