---
apiVersion: v1
kind: Service
metadata:
  name: atst-main
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cloudzero-{{ namespace }}-public"
---
apiVersion: v1
kind: Service
metadata:
  name: atst-auth
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cloudzero-{{ namespace }}-public"
