---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
data:
  CAC_URL: https://auth-master.atat.dev/login-redirect
  CELERY_DEFAULT_QUEUE: celery-master
  FLASK_ENV: master
  PGDATABASE: cloudzero_pwdev_atat_master
  SERVER_NAME: master.atat.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-envvars
data:
  CAC_URL: https://auth-master.atat.dev/login-redirect
  CDN_ORIGIN: https://master.atat.dev
  CELERY_DEFAULT_QUEUE: celery-master
  FLASK_ENV: master
  PGDATABASE: cloudzero_pwdev_atat_master
  STATIC_URL: "https://master.atat.dev/static/"
