- op: replace
  path: /spec/template/spec/containers/1/ports/0/containerPort
  value: 8342
- op: replace
  path: /spec/template/spec/containers/1/ports/1/containerPort
  value: 8442
- op: replace
  path: /spec/template/spec/containers/1/ports/2/containerPort
  value: 8343
- op: replace
  path: /spec/template/spec/containers/1/ports/3/containerPort
  value: 8443
