---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atat
  name: atat-app
  namespace: atat
spec:
  template:
    spec:
      containers:
        - name: atat-app
          image: {{ application_container_image }}
        - name: nginx
          image: {{ nginx_container_image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atat
  name: atat-worker
  namespace: atat
spec:
  template:
    spec:
      containers:
        - name: atat-worker
          image: {{ application_container_image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atat
  name: atat-beat
  namespace: atat
spec:
  template:
    spec:
      containers:
        - name: atat-beat
          image: {{ application_container_image }}
