---
apiVersion: v1
kind: Service
metadata:
  name: atat-main
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "{{ aks_node_subnet }}"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ aks_internal_lb_ip }}"
  ports:
    - port: 443
    - port: 80
