---
apiVersion: v1
kind: Service
metadata:
  name: atat-main
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cloudzero-jedidev-public"
spec:
  loadBalancerIP: ""
  ports:
  - port: 80
    targetPort: 9342
    name: http
  - port: 443
    targetPort: 9442
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: atat-auth
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "cloudzero-jedidev-public"
spec:
  loadBalancerIP: ""
  ports:
  - port: 80
    targetPort: 9343
    name: http
  - port: 443
    targetPort: 9443
    name: https
