#!/bin/bash
set -e

# script/cibuild: Run CI related checks and tests

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Run lint/style checks and unit tests
export FLASK_ENV=ci

# Define all relevant python files and directories for this app
PYTHON_FILES="./app.py ./atat/** ./config"

# Enable Python testing
RUN_PYTHON_TESTS="true"
# Python linting occurs elsewhere in the pipeline
RUN_PYTHON_LINT="false"

# Enable Javascript testing
RUN_JS_TESTS="true"

# Run the shared test script
source ./script/include/run_test
