---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atst-worker-envvars
  namespace: atat
data:
  TZ: UTC
  DISABLE_CRL_CHECK: "True"
  CRL_STORAGE_PROVIDER: CLOUDFILES
  REDIS_URI: "redis://redis-svc:6379"
  PGHOST: postgres-svc
