- name: Generate the folder that will hold the Diffie-Hellman file
  file:
    state: directory
    path: /src/ansible/dh

- name: (Async) Generate Diffie-Hellman parameters with the default size of 4096 bits
  openssl_dhparam:
    path: /src/ansible/dh/dhparams.pem
  async: 10000
  poll: 0
  register: diffie_hellman_job_handle
