- name: Create the dh directory if it does not exist
  file:
    path: "{{playbook_dir}}/dh"
    state: directory
    mode: "0755"

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  openssl_dhparam:
    path: "{{playbook_dir}}/dh/dhparams.pem"
