- hosts: localhost
  roles:
    - role: crypto
    - role: bootstrap
    - role: terraform
    - role: destroy_bootstrap
      when: teardown_bootstrap_env is defined
    - role: azure_keyvault
      vars:
        bootstrap_terraform_secrets: "true"
        vault_url: "{{ tf_app_env_outputs.operator_keyvault_url.value }}"
        keyvault_name: "{{ tf_app_env_outputs.operator_keyvault_name.value }}"
        secrets_source: "tfvars"
      when: asdf is defined

    - role: azure_keyvault
      vars:
        bootstrap_terraform_secrets: "false"
        vault_url: "{{ tf_app_env_outputs.application_keyvault_url.value }}"
        secrets_source: "tfoutputs"
        top_level_secrets: true
        keyvault_name: "{{ tf_app_env_outputs.application_keyvault_name.value }}"
      when: asdf is defined
