- hosts: localhost
  roles:
    - role: crypto
    - role: bootstrap
    - role: circle_ci
      vars:
        token_source_tf: true
        build_and_push_app_images: false
    - role: terraform
    - role: circle_ci
      vars:
        token_source_tf: true
        build_and_push_ops_image: false
    - role: destroy_bootstrap
      when: teardown_bootstrap_env is defined
    - role: azure_keyvault
      vars:
        ops_vault_url: "{{ tf_app_env_outputs.operator_keyvault_url.value }}"
        ops_keyvault_name: "{{ tf_app_env_outputs.operator_keyvault_name.value }}"
        app_vault_url: "{{ tf_app_env_outputs.application_keyvault_url.value }}"
        app_keyvault_name: "{{ tf_app_env_outputs.application_keyvault_name.value }}"
