---
apiVersion: v1
kind: Service
metadata:
  name: atst-main
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "{{ aks_subnet }}"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
 spec:
   type: LoadBalancer
   loadBalancerIP: "10.1.2.201"
   ports:
   - port: 443
   - port: 80
