apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: atst-secret-provider
spec:
  provider: azure
  parameters:
    userAssignedIdentityID: "{{ aks_keyvault_reader_client_id }}"
    keyvaultName: "{{ application_keyvault_name }}"          # the name of the KeyVault
    tenantId: "{{ tenant_id }}"                    # the tenant ID of the KeyVault

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nginx-secret-provider
spec:
  provider: azure
  parameters:
    userAssignedIdentityID: "{{ aks_keyvault_reader_client_id }}"
    keyvaultName: "{{ application_keyvault_name }}"          # the name of the KeyVault
    tenantId: "{{ tenant_id }}"                    # the tenant ID of the KeyVault
