---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: atst
  name: atst
  namespace: atat
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atst
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: atst
  name: atst-worker
  namespace: atat
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atst-worker
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
