---
apiVersion: v1
kind: Namespace
metadata:
  name: atat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atat
  name: atat
  namespace: atat
spec:
  selector:
    matchLabels:
      role: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: atat
        role: web
        aadpodidbinding: atat-kv-id-binding
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: atat
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: UWSGI_PROCESSES
              value: "2"
            - name: UWSGI_THREADS
              value: "2"
            - name: UWSGI_ENABLE_THREADS
              value: "1"
          envFrom:
            - configMapRef:
                name: atat-envvars
          volumeMounts:
            - name: uwsgi-socket-dir
              mountPath: "/var/run/uwsgi"
            - name: pgsslrootcert
              mountPath: "/opt/atat/atat/ssl/pgsslrootcert.crt"
              subPath: pgsslrootcert.crt
            - name: uwsgi-config
              mountPath: "/opt/atat/atat/uwsgi.ini"
              subPath: uwsgi.ini
            - name: flask-secret
              mountPath: "/config"
          resources:
            requests:
              memory: 800Mi
              cpu: 940m
            limits:
              memory: 800Mi
              cpu: 940m
        - name: nginx
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8342
              name: main-upgrade
            - containerPort: 8442
              name: main
          volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/"
            - name: uwsgi-socket-dir
              mountPath: "/var/run/uwsgi"
            - name: acme
              mountPath: "/usr/share/nginx/html/.well-known/acme-challenge/"
            - name: snippets
              mountPath: "/etc/nginx/snippets/"
            - name: nginx-secret
              mountPath: "/etc/ssl/"
          resources:
            requests:
              memory: 20Mi
              cpu: 25m
            limits:
              memory: 20Mi
              cpu: 25m
      volumes:
        - name: nginx-config
          configMap:
            name: atat-nginx
        - name: uwsgi-socket-dir
          emptyDir:
            medium: Memory
        - name: pgsslrootcert
          configMap:
            name: pgsslrootcert
            items:
              - key: cert
                path: pgsslrootcert.crt
                mode: 0666
        - name: acme
          configMap:
            name: acme-challenges
            defaultMode: 0666
        - name: uwsgi-config
          configMap:
            name: uwsgi-config
            defaultMode: 0666
            items:
              - key: uwsgi.ini
                path: uwsgi.ini
                mode: 0644
        - name: snippets
          configMap:
            name: nginx-snippets
        - name: nginx-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "nginx-secret-provider"
        - name: flask-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "atat-secret-provider"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atat
  name: atat-worker
  namespace: atat
spec:
  selector:
    matchLabels:
      role: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: atat
        role: worker
        aadpodidbinding: atat-kv-id-binding
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: atat-worker
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          args:
            [
              "/opt/atat/atat/.venv/bin/python",
              "/opt/atat/atat/.venv/bin/celery",
              "-A",
              "celery_worker.celery",
              "worker",
              "--loglevel=INFO",
            ]
          envFrom:
            - configMapRef:
                name: atat-envvars
            - configMapRef:
                name: atat-worker-envvars
          volumeMounts:
            - name: pgsslrootcert
              mountPath: "/opt/atat/atat/ssl/pgsslrootcert.crt"
              subPath: pgsslrootcert.crt
            - name: flask-secret
              mountPath: "/config"
          resources:
            requests:
              memory: 280Mi
              cpu: 400m
            limits:
              memory: 280Mi
              cpu: 400m
      volumes:
        - name: pgsslrootcert
          configMap:
            name: pgsslrootcert
            items:
              - key: cert
                path: pgsslrootcert.crt
                mode: 0666
        - name: flask-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "atat-secret-provider"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atat
  name: atat-beat
  namespace: atat
spec:
  selector:
    matchLabels:
      role: beat
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: atat
        role: beat
        aadpodidbinding: atat-kv-id-binding
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: atat-beat
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          args:
            [
              "/opt/atat/atat/.venv/bin/python",
              "/opt/atat/atat/.venv/bin/celery",
              "-A",
              "celery_worker.celery",
              "beat",
              "--loglevel=INFO",
            ]
          envFrom:
            - configMapRef:
                name: atat-envvars
            - configMapRef:
                name: atat-worker-envvars
          volumeMounts:
            - name: pgsslrootcert
              mountPath: "/opt/atat/atat/ssl/pgsslrootcert.crt"
              subPath: pgsslrootcert.crt
            - name: flask-secret
              mountPath: "/config"
          resources:
            requests:
              memory: 80Mi
              cpu: 10m
            limits:
              memory: 80Mi
              cpu: 10m
      volumes:
        - name: pgsslrootcert
          configMap:
            name: pgsslrootcert
            items:
              - key: cert
                path: pgsslrootcert.crt
                mode: 0666
        - name: flask-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "atat-secret-provider"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: atat
  name: atat-main
  namespace: atat
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8342
      name: http
    - port: 443
      targetPort: 8442
      name: https
  selector:
    role: web
  type: LoadBalancer
