namespace: atat
resources:
  - azure.yml
  - atst-envvars-configmap.yml
  - atst-nginx-configmap.yml
  - atst-worker-envvars-configmap.yml
  - pgsslrootcert.yml
  - acme-challenges.yml
  - nginx-snippets.yml
  - autoscaling.yml
configMapGenerator:
- name: uwsgi-config
  namespace: atat
  files:
  - uwsgi.ini
generatorOptions:
  disableNameSuffixHash: true
