namespace: atat
resources:
  - azure.yml
  - atat-envvars-configmap.yml
  - atat-nginx-configmap.yml
  - atat-worker-envvars-configmap.yml
  - pgsslrootcert.yml
  - acme-challenges.yml
  - nginx-snippets.yml
  - autoscaling.yml
  - pod-security.yml
  - secret_provider.yml
configMapGenerator:
- name: uwsgi-config
  namespace: atat
  files:
  - uwsgi.ini
generatorOptions:
  disableNameSuffixHash: true
