apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restrict-users
spec:
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
