---
apiVersion: v1
kind: Service
metadata:
  name: atst-main
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 443
    - port: 80
