name: Locust Load Test

on:
  push:
    inputs:
      url:
        description: "URL of the deployed ATAT environment to be load tested"
        required: true
      users:
        description: "The number of users to spawn"
        required: true
      rate:
        description: "Spawn this many users per second to ramp-up"
        required: true
      runtime:
        description: "Length of time to run the load test.  For example, 10s, 1m, 1h"
        required: true

jobs:
  loadtest:
    name: "Run load test"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ATAT repo
        uses: actions/checkout@v2
      - name: Build locust.io docker container
        working-directory: /home/runner/work/atat/atat/load-test
        run: |
          docker build -t locust .
      - name: Initiate the load test
        run: |
           docker run --rm -p 8089:8089 -e DISABLE_VERIFY=true locust:latest -H ${{ github.events.inputs.url }}